AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Alarm Lab - Deploys two EC2 instances for alarm configuration (Fixed Version)'

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
    ConstraintDescription: Must be a valid EC2 instance type.
  
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Latest Amazon Linux 2 AMI from SSM Parameter Store

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CloudWatch-Alarm-Lab-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CloudWatch-Alarm-Lab-IGW

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: CloudWatch-Alarm-Lab-Public-Subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: CloudWatch-Alarm-Lab-Public-RT

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2InstanceRole

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      SubnetId: !Ref PublicSubnet
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: !Ref LatestAmiId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd stress-ng php php-cli
          
          # Create a simple bash script to run stress-ng
          cat > /usr/local/bin/run-stress.sh << 'EOF'
          #!/bin/bash
          /usr/bin/stress-ng --cpu 1 --timeout 600s > /tmp/stress.log 2>&1 &
          echo $! > /tmp/cpu_load_pid
          chmod 666 /tmp/cpu_load_pid
          EOF
          
          # Create a simple bash script to stop stress-ng
          cat > /usr/local/bin/stop-stress.sh << 'EOF'
          #!/bin/bash
          if [ -f /tmp/cpu_load_pid ]; then
            kill -9 $(cat /tmp/cpu_load_pid)
            rm -f /tmp/cpu_load_pid
            echo "Process stopped"
          else
            echo "No process running"
          fi
          EOF
          
          # Make scripts executable
          chmod 755 /usr/local/bin/run-stress.sh
          chmod 755 /usr/local/bin/stop-stress.sh
          
          # Create CPU load test page
          cat > /var/www/html/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>CPU Load Test</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 0; padding: 20px; line-height: 1.6; }
                  .container { max-width: 800px; margin: 0 auto; padding: 20px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
                  h1 { color: #333; }
                  button { background-color: #4CAF50; border: none; color: white; padding: 10px 20px; text-align: center; 
                          text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 4px; }
                  button.stop { background-color: #f44336; }
                  .status { margin-top: 20px; padding: 10px; border-radius: 4px; }
                  .running { background-color: #ffeb3b; }
                  .stopped { background-color: #e0e0e0; }
                  pre { background-color: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>EC2 CPU Load Test - Instance 1</h1>
                  <p>Use the buttons below to start or stop a CPU load test. This will help trigger CloudWatch alarms.</p>
                  
                  <button id="startBtn" onclick="startLoad()">Start CPU Load (10 minutes)</button>
                  <button id="stopBtn" class="stop" onclick="stopLoad()" disabled>Stop CPU Load</button>
                  
                  <div id="status" class="status stopped">
                      Status: No CPU load test running
                  </div>
                  
                  <div id="response"></div>
                  
                  <script>
                      function startLoad() {
                          document.getElementById('startBtn').disabled = true;
                          document.getElementById('stopBtn').disabled = false;
                          document.getElementById('status').innerHTML = 'Status: Starting CPU load test...';
                          document.getElementById('status').className = 'status running';
                          
                          fetch('/start-load.php')
                              .then(response => response.text())
                              .then(data => {
                                  document.getElementById('response').innerHTML = data;
                                  
                                  // Auto-update status after 10 minutes
                                  setTimeout(function() {
                                      document.getElementById('status').innerHTML = 'Status: CPU load test completed';
                                      document.getElementById('status').className = 'status stopped';
                                      document.getElementById('startBtn').disabled = false;
                                      document.getElementById('stopBtn').disabled = true;
                                  }, 600000);
                              });
                      }
                      
                      function stopLoad() {
                          document.getElementById('startBtn').disabled = false;
                          document.getElementById('stopBtn').disabled = true;
                          document.getElementById('status').innerHTML = 'Status: Stopping CPU load test...';
                          document.getElementById('status').className = 'status stopped';
                          
                          fetch('/stop-load.php')
                              .then(response => response.text())
                              .then(data => {
                                  document.getElementById('response').innerHTML = data;
                              });
                      }
                  </script>
              </div>
          </body>
          </html>
          EOF
          
          # Create PHP scripts to start and stop CPU load
          cat > /var/www/html/start-load.php << 'EOF'
          <?php
          error_reporting(E_ALL);
          ini_set('display_errors', 1);
          
          $output = shell_exec('/usr/local/bin/run-stress.sh 2>&1');
          echo "Command executed.<br>";
          echo "Output: <pre>$output</pre>";
          
          // Verify the process is running
          sleep(1);
          if (file_exists('/tmp/cpu_load_pid')) {
              $pid = file_get_contents('/tmp/cpu_load_pid');
              $ps_output = shell_exec("ps -p $pid");
              echo "Process status: <pre>$ps_output</pre>";
              
              // Show CPU usage
              echo "Current CPU usage: <pre>";
              echo shell_exec("top -b -n 1 | head -20");
              echo "</pre>";
          } else {
              echo "Warning: PID file not created. Process may not have started.";
          }
          ?>
          EOF
          
          cat > /var/www/html/stop-load.php << 'EOF'
          <?php
          error_reporting(E_ALL);
          ini_set('display_errors', 1);
          
          $output = shell_exec('/usr/local/bin/stop-stress.sh 2>&1');
          echo "Command executed.<br>";
          echo "Output: <pre>$output</pre>";
          
          // Show CPU usage after stopping
          echo "Current CPU usage: <pre>";
          echo shell_exec("top -b -n 1 | head -20");
          echo "</pre>";
          ?>
          EOF
          
          # Set proper permissions
          chmod 755 /var/www/html/*.php
          chmod 777 /tmp
          
          # Configure SELinux if enabled
          if command -v sestatus &> /dev/null && sestatus | grep -q "SELinux status: *enabled"; then
            yum install -y policycoreutils-python
            setsebool -P httpd_can_network_connect 1
            setsebool -P httpd_execmem 1
            setsebool -P httpd_can_exec_content 1
            semanage fcontext -a -t httpd_sys_rw_content_t "/tmp(/.*)?"
            restorecon -Rv /tmp
          fi
          
          # Start Apache
          systemctl start httpd
          systemctl enable httpd
      Tags:
        - Key: Name
          Value: CloudWatch-Alarm-Lab-Instance-1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      SubnetId: !Ref PublicSubnet
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: !Ref LatestAmiId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd stress-ng php php-cli
          
          # Create a simple bash script to run stress-ng
          cat > /usr/local/bin/run-stress.sh << 'EOF'
          #!/bin/bash
          /usr/bin/stress-ng --cpu 1 --timeout 600s > /tmp/stress.log 2>&1 &
          echo $! > /tmp/cpu_load_pid
          chmod 666 /tmp/cpu_load_pid
          EOF
          
          # Create a simple bash script to stop stress-ng
          cat > /usr/local/bin/stop-stress.sh << 'EOF'
          #!/bin/bash
          if [ -f /tmp/cpu_load_pid ]; then
            kill -9 $(cat /tmp/cpu_load_pid)
            rm -f /tmp/cpu_load_pid
            echo "Process stopped"
          else
            echo "No process running"
          fi
          EOF
          
          # Make scripts executable
          chmod 755 /usr/local/bin/run-stress.sh
          chmod 755 /usr/local/bin/stop-stress.sh
          
          # Create CPU load test page
          cat > /var/www/html/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>CPU Load Test</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 0; padding: 20px; line-height: 1.6; }
                  .container { max-width: 800px; margin: 0 auto; padding: 20px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
                  h1 { color: #333; }
                  button { background-color: #4CAF50; border: none; color: white; padding: 10px 20px; text-align: center; 
                          text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 4px; }
                  button.stop { background-color: #f44336; }
                  .status { margin-top: 20px; padding: 10px; border-radius: 4px; }
                  .running { background-color: #ffeb3b; }
                  .stopped { background-color: #e0e0e0; }
                  pre { background-color: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>EC2 CPU Load Test - Instance 2</h1>
                  <p>Use the buttons below to start or stop a CPU load test. This will help trigger CloudWatch alarms.</p>
                  
                  <button id="startBtn" onclick="startLoad()">Start CPU Load (10 minutes)</button>
                  <button id="stopBtn" class="stop" onclick="stopLoad()" disabled>Stop CPU Load</button>
                  
                  <div id="status" class="status stopped">
                      Status: No CPU load test running
                  </div>
                  
                  <div id="response"></div>
                  
                  <script>
                      function startLoad() {
                          document.getElementById('startBtn').disabled = true;
                          document.getElementById('stopBtn').disabled = false;
                          document.getElementById('status').innerHTML = 'Status: Starting CPU load test...';
                          document.getElementById('status').className = 'status running';
                          
                          fetch('/start-load.php')
                              .then(response => response.text())
                              .then(data => {
                                  document.getElementById('response').innerHTML = data;
                                  
                                  // Auto-update status after 10 minutes
                                  setTimeout(function() {
                                      document.getElementById('status').innerHTML = 'Status: CPU load test completed';
                                      document.getElementById('status').className = 'status stopped';
                                      document.getElementById('startBtn').disabled = false;
                                      document.getElementById('stopBtn').disabled = true;
                                  }, 600000);
                              });
                      }
                      
                      function stopLoad() {
                          document.getElementById('startBtn').disabled = false;
                          document.getElementById('stopBtn').disabled = true;
                          document.getElementById('status').innerHTML = 'Status: Stopping CPU load test...';
                          document.getElementById('status').className = 'status stopped';
                          
                          fetch('/stop-load.php')
                              .then(response => response.text())
                              .then(data => {
                                  document.getElementById('response').innerHTML = data;
                              });
                      }
                  </script>
              </div>
          </body>
          </html>
          EOF
          
          # Create PHP scripts to start and stop CPU load
          cat > /var/www/html/start-load.php << 'EOF'
          <?php
          error_reporting(E_ALL);
          ini_set('display_errors', 1);
          
          $output = shell_exec('/usr/local/bin/run-stress.sh 2>&1');
          echo "Command executed.<br>";
          echo "Output: <pre>$output</pre>";
          
          // Verify the process is running
          sleep(1);
          if (file_exists('/tmp/cpu_load_pid')) {
              $pid = file_get_contents('/tmp/cpu_load_pid');
              $ps_output = shell_exec("ps -p $pid");
              echo "Process status: <pre>$ps_output</pre>";
              
              // Show CPU usage
              echo "Current CPU usage: <pre>";
              echo shell_exec("top -b -n 1 | head -20");
              echo "</pre>";
          } else {
              echo "Warning: PID file not created. Process may not have started.";
          }
          ?>
          EOF
          
          cat > /var/www/html/stop-load.php << 'EOF'
          <?php
          error_reporting(E_ALL);
          ini_set('display_errors', 1);
          
          $output = shell_exec('/usr/local/bin/stop-stress.sh 2>&1');
          echo "Command executed.<br>";
          echo "Output: <pre>$output</pre>";
          
          // Show CPU usage after stopping
          echo "Current CPU usage: <pre>";
          echo shell_exec("top -b -n 1 | head -20");
          echo "</pre>";
          ?>
          EOF
          
          # Set proper permissions
          chmod 755 /var/www/html/*.php
          chmod 777 /tmp
          
          # Configure SELinux if enabled
          if command -v sestatus &> /dev/null && sestatus | grep -q "SELinux status: *enabled"; then
            yum install -y policycoreutils-python
            setsebool -P httpd_can_network_connect 1
            setsebool -P httpd_execmem 1
            setsebool -P httpd_can_exec_content 1
            semanage fcontext -a -t httpd_sys_rw_content_t "/tmp(/.*)?"
            restorecon -Rv /tmp
          fi
          
          # Start Apache
          systemctl start httpd
          systemctl enable httpd
      Tags:
        - Key: Name
          Value: CloudWatch-Alarm-Lab-Instance-2

Outputs:
  Instance1Id:
    Description: ID of the first EC2 instance
    Value: !Ref EC2Instance1
    Export:
      Name: !Sub "${AWS::StackName}-Instance1Id"

  Instance2Id:
    Description: ID of the second EC2 instance
    Value: !Ref EC2Instance2
    Export:
      Name: !Sub "${AWS::StackName}-Instance2Id"

  Instance1URL:
    Description: URL for the first EC2 instance CPU load test page
    Value: !Sub "http://${EC2Instance1.PublicDnsName}"
    Export:
      Name: !Sub "${AWS::StackName}-Instance1URL"

  Instance2URL:
    Description: URL for the second EC2 instance CPU load test page
    Value: !Sub "http://${EC2Instance2.PublicDnsName}"
    Export:
      Name: !Sub "${AWS::StackName}-Instance2URL"

  VPCId:
    Description: ID of the VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"
